from abc import abstractmethod

from olap3.abstract.olap_source import OLAPSource

schemaElementTypes = {
    "CATALOG": {"RESTRICTION_NAME": "CATALOG_NAME",
                "PROPERTY_NAME": "CATALOG_NAME",
                "ELEMENT_CLASS": "XMLACatalog",
                "XMLA_FUNC": "getDBSchemaCatalogs",
                "RESTRICT_ON": []},
    "CUBE": {"RESTRICTION_NAME": "CUBE_NAME",
             "PROPERTY_NAME": "CUBE_NAME",
             "ELEMENT_CLASS": "XMLACube",
             "XMLA_FUNC": "getMDSchemaCubes",
             "RESTRICT_ON": []},
    "HIERARCHY": {"RESTRICTION_NAME": "HIERARCHY_UNIQUE_NAME",
                  "PROPERTY_NAME": "HIERARCHY_UNIQUE_NAME",
                  "ELEMENT_CLASS": "XMLAHierarchy",
                  "XMLA_FUNC": "getMDSchemaHierarchies",
                  "RESTRICT_ON": ["CUBE"]},
    "DIMENSION_HIERARCHY": {"RESTRICTION_NAME": "HIERARCHY_UNIQUE_NAME",
                            "PROPERTY_NAME": "HIERARCHY_UNIQUE_NAME",
                            "ELEMENT_CLASS": "XMLAHierarchy",
                            "XMLA_FUNC": "getMDSchemaHierarchies",
                            "RESTRICT_ON": ["DIMENSION"]},
    "CATALOG_HIERARCHY": {"RESTRICTION_NAME": "HIERARCHY_UNIQUE_NAME",
                          "PROPERTY_NAME": "HIERARCHY_UNIQUE_NAME",
                          "ELEMENT_CLASS": "XMLAHierarchy",
                          "XMLA_FUNC": "getMDSchemaHierarchies",
                          "RESTRICT_ON": []},
    "DIMENSION": {"RESTRICTION_NAME": "DIMENSION_UNIQUE_NAME",
                  "PROPERTY_NAME": "DIMENSION_UNIQUE_NAME",
                  "ELEMENT_CLASS": "XMLADimension",
                  "XMLA_FUNC": "getMDSchemaDimensions",
                  "RESTRICT_ON": ["CUBE"]},
    "CATALOG_DIMENSION": {"RESTRICTION_NAME": "DIMENSION_UNIQUE_NAME",
                          "PROPERTY_NAME": "DIMENSION_UNIQUE_NAME",
                          "ELEMENT_CLASS": "XMLADimension",
                          "XMLA_FUNC": "getMDSchemaDimensions",
                          "RESTRICT_ON": []},
    "MEASURE": {"RESTRICTION_NAME": "MEASURE_UNIQUE_NAME",
                "PROPERTY_NAME": "MEASURE_UNIQUE_NAME",
                "ELEMENT_CLASS": "XMLAMeasure",
                "XMLA_FUNC": "getMDSchemaMeasures",
                "RESTRICT_ON": ["CUBE"]},
    "CATALOG_MEASURE": {"RESTRICTION_NAME": "MEASURE_UNIQUE_NAME",
                        "PROPERTY_NAME": "MEASURE_UNIQUE_NAME",
                        "ELEMENT_CLASS": "XMLAMeasure",
                        "XMLA_FUNC": "getMDSchemaMeasures",
                        "RESTRICT_ON": []},
    "SET": {"RESTRICTION_NAME": "SET_NAME",
            "PROPERTY_NAME": "SET_NAME",
            "ELEMENT_CLASS": "XMLASet",
            "XMLA_FUNC": "getMDSchemaSets",
            "RESTRICT_ON": ["CUBE"]},
    "CATALOG_SET": {"RESTRICTION_NAME": "SET_NAME",
                    "PROPERTY_NAME": "SET_NAME",
                    "ELEMENT_CLASS": "XMLASet",
                    "XMLA_FUNC": "getMDSchemaSets",
                    "RESTRICT_ON": []},
    "LEVEL": {"RESTRICTION_NAME": "LEVEL_UNIQUE_NAME",
              "PROPERTY_NAME": "LEVEL_UNIQUE_NAME",
              "ELEMENT_CLASS": "XMLALevel",
              "XMLA_FUNC": "getMDSchemaLevels",
              "RESTRICT_ON": ["CUBE", "HIERARCHY"]},
    "MEMBER": {"RESTRICTION_NAME": "MEMBER_UNIQUE_NAME",
               "PROPERTY_NAME": "MEMBER_UNIQUE_NAME",
               "ELEMENT_CLASS": "XMLAMember",
               "XMLA_FUNC": "getMDSchemaMembers",
               "RESTRICT_ON": ["CUBE", "HIERARCHY", "LEVEL"]},
    "HIERARCHY_MEMBER": {"RESTRICTION_NAME": "MEMBER_UNIQUE_NAME",
                         "PROPERTY_NAME": "MEMBER_UNIQUE_NAME",
                         "ELEMENT_CLASS": "XMLAMember",
                         "XMLA_FUNC": "getMDSchemaMembers",
                         "RESTRICT_ON": ["CUBE", "HIERARCHY"]},
    "DIMENSION_MEMBER": {"RESTRICTION_NAME": "MEMBER_UNIQUE_NAME",
                         "PROPERTY_NAME": "MEMBER_UNIQUE_NAME",
                         "ELEMENT_CLASS": "XMLAMember",
                         "XMLA_FUNC": "getMDSchemaMembers",
                         "RESTRICT_ON": ["DIMENSION"]},
    "CUBE_DIMENSION_MEMBER": {"RESTRICTION_NAME": "MEMBER_UNIQUE_NAME",
                              "PROPERTY_NAME": "MEMBER_UNIQUE_NAME",
                              "ELEMENT_CLASS": "XMLAMember",
                              "XMLA_FUNC": "getMDSchemaMembers",
                              "RESTRICT_ON": ["CUBE", "DIMENSION"]},
    "TREE_MEMBER": {"RESTRICTION_NAME": "MEMBER_UNIQUE_NAME",
                    "PROPERTY_NAME": "MEMBER_UNIQUE_NAME",
                    "ELEMENT_CLASS": "XMLAMember",
                    "XMLA_FUNC": "getMDSchemaMembers",
                    "RESTRICT_ON": ["CUBE", "HIERARCHY"]},
    "PROPERTY": {"RESTRICTION_NAME": "PROPERTY_NAME",
                 "PROPERTY_NAME": "PROPERTY_NAME",
                 "ELEMENT_CLASS": "XMLAProperty",
                 "XMLA_FUNC": "getMDSchemaProperties",
                 "RESTRICT_ON": ["CUBE", "HIERARCHY", "LEVEL"]}

}


class XMLASource(OLAPSource):

    @staticmethod
    @abstractmethod
    def getSchemaElements(schemaElementType, unique_name,
                          aslist=False, more_restrictions=None,
                          more_properties=None,
                          generate_instance=True):
        ...

